# Generated by Django 3.2.12 on 2022-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0003_add_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
